version: "3"

services:
  db:
    container_name: pg-db
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
