"""Add column

Revision ID: 0daa2922fb7c
Revises: b31900d1b888
Create Date: 2023-12-18 19:15:47.037622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0daa2922fb7c'
down_revision: Union[str, None] = 'b31900d1b888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'user_id')
    # ### end Alembic commands ###
